### PR TITLE
Setup: Add self-upgrade

### PR DESCRIPTION
**Pull request by dmlemos**
This PR includes some improvements to the `setup.py` script in order to add upgrade option. Requirements are now installed as part of the setup.

I have been using this for a long time but have been frustrated by the lack of upgrade, mainly because I never knew what changed. Because my dotfiles are all symlinked I couldn't just use the `setup.py install` after `git pull`. Instead I am relying on custom scripts.
I think it is easier to upgrade now when new code is available. If needed, migration paths can be catered, since it always uses the `setup.py` in master. It installs the new files without overriding `cmus-osx.config`.

Introduced `argparse` to make it easier to use positional arguments.

To develop locally, just use:
```
ENV=dev ./setup.py install
```

It may not be the best approach to it, but it works 😃
Please let me know your thoughts!

### CODE REVIEW

**Comment by PhilipTrauner** [comment]
Here's the thing: I'm not particularly happy with the current setup script because it assumes that all dependencies should be installed system-wide, instead of inside a virtual environment. Your improvements **definitely** make it better, then it previously was, but I think the best solution would be writing and upstreaming a `brew` formula (which do provide virtual environments for Python applications) that installs an installation helper command line utility in the same vein as the current `setup.py` (which just modifies the `rc` and possibly also sets the `status_display_program` if there isn't one set already to point to the virtual environment managed by `brew`).

**Comment by dmlemos** [comment]
Managed virtualenv provided by `brew` or `pipx` is the right direction. Nonetheless, the setup should not care if there is a virtualenv activated or not. The user is in control wether she wants a virtualenv for cmus or otherwise use the global installation. With brew or pyenv, it is easy not to mess with the system python, therefore is a possible option to install dependencies.

Regarding the brew formula I wasn't sure what their policies were for plugins, but after checking, it seems we should be ok.
However the repository might need some changes for it to work than I remember:
* The formula can't use github releases as there hasn't been any since 2017, and if it uses master branch, there is a risk it might contain broken code (although not any different than it is now)
* With a formula, it makes sense to get rid of the `cmus-osx` folder and store `cmus-osx.config`, inside the cmus installation
* How about local development?

The changes were never meant to replace a brew formula, but perhaps to serve as a preliminary solution until then.

**Comment by PhilipTrauner** [comment]
Here's what I'm planning to do:
1. Write a command line bootstrapping utility that deals with modifying the `rc` and `autosave` to point to the `notify.py` and `media-keys.py` files in the correct Python environment (either a virtual environment or the global Python installation depending on the execution context)  
2. Add an `config` subcommand to said bootstrapping utility that opens the config file with the default `$EDITOR` 
3. Rely on [appdirs](https://pypi.org/project/appdirs/) to supply the config path
4. Migrate to `poetry`  
`poetry` is a virtual environment / dependency manager that always installs packages in editable mode while developing, but can also build regular Python packages. This will make development a breeze 🌊
5. Properly use GitHub releases and upload the resulting Python package builds (possibly with a CI solution, but not sure about that point yet)
6. Publish the resulting package to `pypi` and create a `brew` formula

**Comment by dmlemos** [comment]
That's a substantial upgrade. Great plan!

I am not a fan of `appdirs` for this use case, since `cmus` is a cmd program. Doesn't make much sense to store the config away from it imo.
Not familiar with poetry, but seems like pipenv.

**Comment by PhilipTrauner** [comment]
Fair enough, will instead place the config file at the root of the `cmus` configuration directory 🙂

**Comment by PhilipTrauner** [comment]
It took way longer than expected, but `v3.0.0` (technically `v3.0.1` because I initially forgot to include the `README.md` for PyPI) is finally complete 🙂
I basically implemented every item on the feature list, expect for the `brew` formula, which will follow suit whenever I have some more spare time on my hands. Please take it for a spin and don't hesitate to reach out if you find any bugs 😄

**Comment by dmlemos** [comment]
Sorry for the delay.

What happened to `display_mode`?

**Comment by PhilipTrauner** [comment]
No problem 🙂
I removed the setting because no other music player (that I know of at least) leaves around notifications for previous songs. Should I re-introduce it?

**Comment by dmlemos** [comment]
I prefer not leaving notifications. It is kind useless and just clutter in my opinion.

**Comment by PhilipTrauner** [comment]
Me too. That would map to `display_mode` = `2`, which is the current behavior.

**Comment by dmlemos** [comment]
Overall it works great, but I found some annoyances. Will open new issues.

`exception_hook` is great for debugging :D

**Pull request closed without merging**
